### ISSUE TITLE
Standalone panic on Select when setting WithAccessible(), and then calling Run()

### ISSUE THREAD

**Issue by rusq** [charmbracelet/huh#91]
Hey team, happy new year!

**Describe the bug**
When setting `Select.WithAccessible(true)`, and then `Run`'ning, it causes panic:
```
.../huh@v0.2.3/field_select.go:290 +0x5f
```
[Line 290](https://github.com/charmbracelet/huh/blob/47340b543539f18164c297002be9ac182a8cec65/field_select.go#L290):
```
sb.WriteString(s.theme.Focused.Title.Render(s.title) + "\n")
```

**To Reproduce**
Sample code:
```go
	var resp string
	q := huh.NewSelect[string]().
		Options(
			huh.NewOptions("one", "two", "three")...,
		).
		Title("What would you like to do?").
		Value(&resp).
		WithAccessible(p.accessible)
	if err := q.Run(); err != nil {
		return err
	}
```

Panic happens on Run.

**Expected behavior**
No panic.

**Screenshots**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x310 pc=0x1afeddf]

goroutine 1 [running]:
github.com/charmbracelet/huh.(*Select[...]).runAccessible(0x0)
	/Users/rustam/go/pkg/mod/github.com/charmbracelet/huh@v0.2.3/field_select.go:290 +0x5f
github.com/charmbracelet/huh.(*Select[...]).Run(0x0?)
	/Users/rustam/go/pkg/mod/github.com/charmbracelet/huh@v0.2.3/field_select.go:281 +0x25
main.Interactive(0xc000331680)
	/Users/rustam/wp/_github/slackdump/cmd/slackdump/interactive.go:63 +0x57f
main.main()
	/Users/rustam/wp/_github/slackdump/cmd/slackdump/main.go:98 +0x426
exit status 2
```

**Desktop (please complete the following information):**
 - Version v0.2.3

**Comment by maaslalani** [comment]
Hey! Thanks so much for creating this issue, I was able to reproduce!

This is fixed by https://github.com/charmbracelet/huh/pull/92
